version: "3.7"
services:
  influxdb:
    container_name: influxdb
    build:
      dockerfile: Dockerfile
      context: ./influxdb
    ports:
    - 8086:8086
    volumes:
    - /opt/influxdb:/var/lib/influxdb
    restart: always

  telegraf:
    container_name: telegraf
    volumes:
    - /:/hostfs:ro
    - /var/run/utmp:/hostfs/var/run/utmp:ro
    - /opt/configs/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf

    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
    build:
      dockerfile: Dockerfile
      context: ./telegraf
    network_mode: host
    restart: always

  grafana:
    image: grafana/grafana:6.5.0
    volumes:
    - /opt/grafana:/var/lib/grafana
    ports:
    - 3000:3000
    restart: always

  loki:
    image: grafana/loki:1.5.0
    volumes:
    - /opt/configs/loki:/config
    - /opt/loki:/loki
    ports:
      - "3100:3100"
    command: -config.file=/config/loki-config.yaml
    restart: always

  promtail:
    image: grafana/promtail:1.5.0
    ports:
      - 1514:1514
    volumes:
      - /opt/configs/promtail:/config
      - /opt/promtail:/promtail
      - /:/hostfs:ro
    command: -config.file=/config/promtail-config.yaml
    restart: always
